### PR TITLE
Update Go version to 1.19

### PR DESCRIPTION
**Pull request by sagikazarmark**
This PR updates Go to the latest version as well as ensures that hostctl can be compiled on the latest Darwin version with the latest go version.

### CODE REVIEW

**Comment by guumaster** [comment]
Hi @sagikazarmark, many thanks for all this work! I'll be happy to read and merge it. It will take some time, but at first glance it looks all good!

Did you have the chance to run the Github actions?

**Comment by sagikazarmark** [comment]
Hi @guumaster! Thanks!

I've tested some of the flows manually, but not the actions themselves directly. That seems like a hard thing to do.

**Comment by sagikazarmark** [comment]
@guumaster did you have a chance to take a look at this PR?

**Comment by guumaster** [comment]
v1.1.3 published with Go v1.19 🎉   

Thanks!

**Comment by sagikazarmark** [comment]
Thanks!

**Pull request merged**
